[phases.setup]
nixPkgs = ["nodejs-18_x", "yarn"]

[phases.install]
cmds = [
  "yarn install",
  "cd server && npx playwright install-deps chromium",
  "cd server && npx playwright install chromium"
]

[phases.build]
cmds = ["yarn client:build"]

[start]
cmd = "yarn start"

